Allow creating outputs file when simulation starts at non-zero time
TEAR-ERC/tandem pull request #60
Opened 2023-10-12 22:08 UTC by JeenaYun

The changes are made to allow the creation of probe outputs when the simulation starts at non-zero time. This feature might be useful in the case of loading checkpoints.

2023-10-12 22:15 UTC, hpc4geo requested changes
Please update the code

2023-10-12 22:15 UTC, hpc4geo commented on src/io/BoundaryProbeWriter.cpp
> +                // open existing file
Please remove all these comments

2023-10-12 22:15 UTC, hpc4geo commented on src/io/ScalarWriter.cpp
> +            // open existing file
Please delete all these comments

2023-10-12 22:15 UTC, hpc4geo commented on src/io/BoundaryProbeWriter.cpp
> +            fs::path pckp(probe.file_name);
Remove lines 88-90 and replace with just

```
if (std::filesystem::exists(probe.file_name)) {
```

2023-10-12 22:15 UTC, hpc4geo commented on src/io/BoundaryProbeWriter.cpp
> +namespace fs = std::filesystem;
Remove line 12 (uneeded - see below)

2023-10-12 22:15 UTC, hpc4geo commented on src/io/ScalarWriter.cpp
> +namespace fs = std::filesystem;
Remove line 6

2023-10-12 22:15 UTC, hpc4geo commented on src/io/ScalarWriter.cpp
> +        if (exists) {
Replace lines 24-26 with 
```
if (std::filesystem::exists(file_name_)) {
```

2023-10-12 22:26 UTC, JeenaYun commented
Hi, thanks for the comment. I reflected your suggestions.

2023-10-12 23:24 UTC, dmay23 commented
You have the wrong file name in ScalarWritwr.cpp. You refer to
probe.file_name in the if() statement.

Always check the code compiles before committing and pushing.

On Thu 12. Oct 2023 at 15:26, Jeena Yun ***@***.***> wrote:

> Hi, thanks for the comment. I reflected your suggestions.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/TEAR-ERC/tandem/pull/60#issuecomment-1760455945>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADO6RJ2GXUYQDXE67OZSUJLX7BVB3ANCNFSM6AAAAAA56IGZUE>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2023-10-13 00:18 UTC, JeenaYun commented
I followed the convention used inside the file ScalarWriter.cpp. The variable name pointing to the file name is already `file_name_` not `probe.file_name` even before my commit. I guess it is because ScalarWriter.cpp is not related to 'probe' outputs, but rather used for fault scalar output. Correct me if I am wrong.

2023-10-13 00:39 UTC, hpc4geo commented
> I followed the convention used inside the file ScalarWriter.cpp. The variable name pointing to the file name is already `file_name_` not `probe.file_name` even before my commit. I guess it is because ScalarWriter.cpp is not related to 'probe' outputs, but rather used for fault scalar output. Correct me if I am wrong.

```
symgrad:~/codes/tandem/src/io % grep probe ScalarWriter.cpp  
symgrad:~/codes/tandem/src/io %                                             <dmay/seas-checkpoint>
```
There is no reference to anything called `probe` in ScalarWriter.cpp

2023-10-13 00:45 UTC, JeenaYun commented
Oh I see what you mean. That was a typo, sorry.

2023-10-13 00:49 UTC, dmay23 commented
Attempting to compile the code would have exposed this typo….

On Thu 12. Oct 2023 at 17:46, Jeena Yun ***@***.***> wrote:

> Oh I see what you mean. That was a typo, sorry.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/TEAR-ERC/tandem/pull/60#issuecomment-1760597730>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ADO6RJYM5SVSRZF4XZ3SKXLX7CFMZANCNFSM6AAAAAA56IGZUE>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2023-10-13 19:38 UTC, hpc4geo approved these changes
Thanks for your contribution Jeena.

2023-10-13 19:39 UTC, merged